### PR TITLE
fix: remove comment that shows up in clap help text

### LINKED ISSUE #85: The comment of the Verbosity struct shows up in latest clap
After updating all dependencies, the comment of `/// Logging flags to `#[command(flatte)]` into your CLI` shows up as the first line in our help text. I don't think that's intended.

```
Logging flags to `#[command(flatte)]` into your CLI

Usage: rattler-build [OPTIONS] [COMMAND]

Commands:
  build       Build a package
  test        Test a package
...
```

I can send a patch to remove this comment, but also happy to hear other options.

### PR DESCRIPTION
**Pull request by wolfv**
fixes #85

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -60,7 +60,6 @@
 pub use log::Level;
 pub use log::LevelFilter;
 
-/// Logging flags to `#[command(flatten)]` into your CLI
 #[derive(clap::Args, Debug, Clone, Default)]
```
Comment (epage) [inline src/lib.rs:63]:
```suggestion
/// Logging flags to `#[command(flatten)]` into your CLI
#[derive(clap::Args, Debug, Clone, Default)]
#[command(about = None, long_about = None)]
```

**Comment by wolfv** [comment]
Thanks @epage !

**Comment by wolfv** [comment]
Thanks, and also thanks for the release! 🚀
